ElixirPhoenix/Running_a_CNN_inTensorFlow_usingTheFunctionalProgramming/ElxPhonxProj/discuss/web/router.ex
defmodule Discuss.Router do
  use Discuss.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
	plug Discuss.Plugs.SetUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  @moduledoc """
  This Router module helps in redirecting the application based on the user request. It controls in routing the requests of user t the relevant functions.
  """  
  
  scope "/", Discuss do
    pipe_through :browser # Use the default browser stack
    
	get "/", PageController, :index

	
	get "/topics/welcome" , TopicController, :welcome
	get "/topics/hillroom/mnist/startindex", TopicController, :startindex
	get "/topics/hillroom/mnist/startindex/useapp", TopicController, :useapp
	post "/topics/hillroom/mnist/startindex/classify", TopicController,:classifyimage
	post "/topics/hillroom/mnist/startindex", TopicController, :startindex
  end
  
  
    scope "/auth", Discuss do
    pipe_through :browser
    get "/signout", AuthController, :signout
    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
	
  end
  

  # Other scopes may use custom stacks.
   scope "/api", Discuss do
     pipe_through :api	
	 resources "/topics/hillroom/mnist/startindex", TopicController		
   end
end

ElixirPhoenix/Running_a_CNN_inTensorFlow_usingTheFunctionalProgramming/ElxPhonxProj/discuss/web/views/layout_view.ex
defmodule Discuss.LayoutView do
  use Discuss.Web, :view
end

ElixirPhoenix/Running_a_CNN_inTensorFlow_usingTheFunctionalProgramming/ElxPhonxProj/discuss/web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>CNN-MNIST testing live!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
	    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  </head>

  <body>
    <div class="container">

	    <nav class="light-blue">
      <div class="nav-wrapper container">
        <a href="/" class="brand-logo">
          Welch Allyn MNIST Naren
        </a>
		<ul class="right">
          <%= if @conn.assigns[:user] do %>
            <li>
              <%= link "Sign Out", to: auth_path(@conn, :signout) %>
            </li>
          <% else %>
            <li>
              <%= link "Sign in with Github", to: auth_path(@conn, :request, "github") %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>